# Generated by Django 3.0.4 on 2020-03-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200326_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auteur',
            new_name='author',
        ),
    ]
